### PR TITLE
Delete idx_to_label.pkl

### PR DESCRIPTION
**Pull request by ptitzler**
Is this file needed in the `/assets/` folder? Close PR if it is.

### CODE REVIEW

**Comment by MLnick** [comment]
Yes it is required:
https://github.com/IBM/MAX-Facial-Emotion-Classifier/blob/0d4a2783cc4280a390c01b8badbc062369a6a367/core/model.py#L66

**Comment by ptitzler** [comment]
Interesting. I've never seen a model runtime dependency on an artifact in the `/assets` directory. I knew some where used to drive tests, but this is a first.

**Comment by MLnick** [comment]
See e.g.
https://github.com/IBM/MAX-Scene-Classifier/blob/master/assets/categories_places365.txt
for
a similar situation

We need the files - but arguably they could be bundled into assets.tar.gz
and unpacked only in the Docker container

**Comment by ptitzler** [comment]
Naw, that's fine. Sorry for breaking the build.

**Pull request closed without merging**
